version: '3.5'

services:
  elastic:
    image: elasticsearch:8.6.2
    hostname: elastic
    container_name: elastic
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - |
        discovery.type=single-node
