version: '3.5'

networks:
  my-network:
    name: network
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - /tmp/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - my-network
    environment:
      - GF_INSTALL_PLUGINS=grafana-github-datasource
