version: '3.8'
services:
  opensearch:
    image: opensearch:2.10.0
    hostname: opensearch
    container_name: opensearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - |
        discovery.type=single-node
