version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    restart: always
  mimir:
    image: grafana/mimir:latest
    ports:
      - 9009:9009
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml
    command:
      - --config.file=/etc/mimir.yaml
    restart: always
  grafana:
    depends_on:
      - prometheus
      - mimir
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - /tmp/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-prometheus.yaml:/etc/grafana/provisioning/datasources/grafana-prometheus.yaml
      - ./grafana-mimir.yaml:/etc/grafana/provisioning/datasources/grafana-mimir.yaml
    restart: always
  agent:
    depends_on:
      - grafana
    image: grafana/agent:latest 
    restart: always
    volumes:
      - /tmp/agent:/etc/agent/data
      - ./agent.yaml:/etc/agent/agent.yaml 
