version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    restart: always
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - /tmp/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    restart: always
  agent:
    dependens_on:
      - grafana
    image: grafana/agent:latest 
    restart: always
    volumes:
      - /tmp/agent:/etc/agent/data
      - ./agent.yaml:/etc/agent/agent.yaml 
