version: '3.3'

services:
  fakeservice:
    build:
      context: ./go-fakeservice
      dockerfile: Dockerfile
    hostname: fakeservice
    ports:
      - 3001:3001
    restart: always
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - /tmp/prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    restart: always
  mimir:
    image: grafana/mimir:latest
    hostname: mimir
    ports:
      - 9009:9009
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml
    command:
      - --config.file=/etc/mimir.yaml
    restart: always
  loki:
    image: grafana/loki:latest
    hostname: loki
    ports:
      - 3100:3100
  grafana:
    depends_on:
      - prometheus
      - mimir
      - loki
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - /tmp/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-prometheus.yaml:/etc/grafana/provisioning/datasources/grafana-prometheus.yaml
      - ./grafana-mimir.yaml:/etc/grafana/provisioning/datasources/grafana-mimir.yaml
      - ./grafana-loki.yaml:/etc/grafana/provisioning/datasources/grafana-loki.yaml
    restart: always
  agent:
    depends_on:
      - grafana
    image: grafana/agent:latest 
    hostname: agent
    restart: always
    volumes:
      - /tmp/agent:/etc/agent/data
      - ./grafana-agent.yaml:/etc/agent/agent.yaml 
