apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100/prometheus
  database:
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    maxLines: 1000
