apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Mimir
  type: prometheus
  access: proxy
  orgId: 1
  url: http://localhost:8080
  database:
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
