apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Mimir
  type: prometheus
  access: proxy
  orgId: 1
  url: http://mimir:9009/prometheus
  database:
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
