server:
  log_level: debug
metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 1m
#    remote_write:
#      - url: http://mimir:9009/api/v1/push
  configs:
    - name: fakeservice-go
      scrape_configs:
        - job_name: fakeservice-go
          static_configs:
            - targets: ['fakeservice-go:3001']
      remote_write:
        - url: http://mimir:9009/api/v1/push
    - name: fakeservice-flink
      scrape_configs:
        - job_name: fakeservice-flink
          static_configs:
            - targets: ['fakeservice-flink-taskmanager:9464'] 
      remote_write:
        - url: http://mimir:9009/api/v1/push

logs:
  configs:
  - name: default
    positions:
        filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              __path__: /var/log/*log

integrations:
  agent:
    enabled: true
